version: "3.9"
services:
  nginx:
    build: nginx
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt

  backend:
    build: backend

volumes:
  nginx_secrets:
