version: "3.9"
services:
  frontend:
    build: frontend
    volumes:
      - ./frontend/:/app/
    ports:
      - 8081:8080

  backend:
    build: backend
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=dev
    ports:
      - 8001:8000
